name = "hugo-basic"
license = "MIT"
licenselink = "https://github.com/devon-wolf/hugo-basic/blob/master/LICENSE"
description = "Basic Hugo theme based on Blank by Vimux"
homepage = "https://github.com/devon-wolf/hugo-basic/"
demosite = ""
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "devon-wolf"
  homepage = "https://github.com/devon-wolf"
